### ISSUE TITLE
Utilizing MRGN (and STR)

### ISSUE THREAD

**Issue by Tarferi** [Buizz/EUD-Editor-3#10]
Could you not? I mean, it's a static field that is accessible for all of our tools and has actual direct meaning for game mechanics. Utilizing it makes other moders restore the section in higher numbered trigger cycles, which adds delay condition into everything. You could investigate range 0x57F0F0 - 0x5967F0 (up to 93kb "free" space) instead.
Same goes for STR. The section size limit is large, but not the directly addressable content. If you could occupy only unaddressable space (or higher half of addressable) that would be very cool (> 0xFFFF). Or you could also leave relocation table behind and leave compression to actual compressors.

**Comment by armoha** [comment]
EUD Editor just provides frontend to users.
EUD Editor just generates codes based on user's savefile and passes it to euddraft. euddraft generates actual scenario.chk, and euddraft already actively utilize MRGN and STR for trigger loop.
If you are familiar with python, you can port your tool into euddraft plugin.

**Comment by armoha** [comment]
Since this is not an issue about EUD Editor itself, but about its dependency, let me answer your report.
As you know, eudplib generates triggers in STR, and connects TRIG to STR with triggers in MRGN.

If possible, you can try to apply your tool to basemap, and insert map into euddraft later.

```
Utilizing it makes other moders restore the section in higher numbered trigger cycles, which adds delay condition into everything.
```
eudplib already saves original MRGN contents and restores them after game starts so you don't need to restore the section for yourself.

```
You could investigate range 0x57F0F0 - 0x5967F0 (up to 93kb "free" space) instead.
```
There is no 93kb free spaces, because we can only utilizes the section of scenario.chk, which has fixed address, and large enough to contain 2 triggers. (4816 bytes at maximum, but we can stack trigger to take up less spaces)
See: http://www.staredit.net/wiki/index.php/Scenario.chk

So candidates for alternative MRGN would be...
**PUNI**: I didn't test it. It is said to `u8`, but maybe only value masked with 1 remains in game.
**UNIx**: It would be nasty to fix hp of all preplaced units.

Alternatively, we can compress/pack MRGN trigger to takes less spaces, about 2600 bytes.
```
If you could occupy only unaddressable space (or higher half of addressable) that would be very cool (> 0xFFFF).
```
It would requires some work on allocator of eudplib, but seems possible.

```
Or you could also leave relocation table behind and leave compression to actual compressors.
```
eudplib already compresses STR section (which contains strings and triggers), so I am not sure why you need other compressors.

**Comment by Tarferi** [comment]
> we can only utilizes the section of scenario.chk, which has fixed address, and large enough to contain 2 triggers.

You can make triggers on the fly anywhere (the cp trick to loop count off triggers and perform jump back from <anywhere safe>). 

> eudplib already saves original MRGN contents and restores them after game starts so you don't need to restore the section for yourself. eudplib adds disable flag to all TRIG triggers other than relocation-related triggers and flip-flop the flag after game starts. So there is no need to add any additional condition.

That is true, if you don't have any other tool in compile toolchain. Otherwise you must restore whatever is not in the map before eudplib gets it (my scenario). What I meant is mark triggers that utilize the sections so that they can be relocated in postprocessing (there are unused flags in every trigger/condition/action)

> eudplib already compresses STR section (which contains strings and triggers), so I am not sure why you need other compressors.

Additional postprocessing that cannot be done prior the eudplib process.

> eudplib is best map compressor than any other tools because it can compress and repeat triggers.

True unless you do your own postprocessing (I do string remapping on the fly to add multilanguage support to <any map>)

> EUD Editor just provides frontend to users.
EUD Editor just generates codes based on user's savefile and passes it to euddraft. euddraft generates actual scenario.chk, and euddraft already actively utilize MRGN and STR for trigger loop.

Thanks, will forward my issue accordingly
