### ISSUE TITLE
Encoding error..

### ISSUE THREAD

**Issue by bluesblue** [Buizz/EUD-Editor-3#36]
As the picture shown,both Korean and Chinese have encoding problem,May I need to modify some settings.
![image](https://user-images.githubusercontent.com/40731683/103747020-f5618180-503c-11eb-91d8-e8c2ccc5e5b1.png)
![image](https://user-images.githubusercontent.com/40731683/103746729-871cbf00-503c-11eb-8026-94aca41a7fdb.png)

**Comment by armoha** [comment]
Can you copy paste original input here?

**Comment by armoha** [comment]
![SCScrnShot_021321_233307](https://user-images.githubusercontent.com/16814706/107853410-3c6f3d80-6e59-11eb-87d7-95903f89aa22.png)

I found a way to make unicode text. (see image)
The requirement is a bit tricky; text should be encoded as UTF-8 and not be able to decoded as CP949.
In other word, text should not have any ambiguity.

For example, `测试` is broken to `役뗨캊` since `测试` in UTF-8 (`E6 B5 8B E8 AF 95`) is decodable in CP949.
(CP949 has higher priority than UTF-8)

As shown in the image, `测试Test테스트 하 다` displays well because `ED` in `테` (`ED 85 8C`) is impossible to decode with CP949 so it falls back to interpret as unicode text.

**Comment by armoha** [comment]
@Buizz EUD Editor 3에서 유니코드 TBL 기능을 지원하려면,
입력한 텍스트를 UTF-8로 인코딩한 바이트열이 CP949로 디코딩 가능한지/불가능한지 여부를 에디터 상에서 보여주고,
UTF-8 TBL이 가능하면 해당 TBL은 .tbl 파일에 UTF-8로 인코딩하여 저장하면 될 거에요.

**Comment by bluesblue** [comment]
Thank you,you help me a lot.In EE2,I can type Traditional Chinese text directly and SC exe will recongnize mostly of them and display correctly.But In EE3,as you see,neither Chinese nor Korean can't be recognize.I don't know much about decoding and encoding,I just guess that EE3 processes encoding wrongly or EE2 uses special way to process encoding.

**Comment by armoha** [comment]
Yeah EE2 always uses Korean character set and EE3 uses your system's set. Korean character set has some Traditional Chinese characters ([list hyperlink](https://en.wiktionary.org/wiki/Index:Korean/Hanja/KS_X_1001_hangyol_code)) so that's why most of them display correctly. On the other hand, EE3 recognize map strings with your system encoding so it correctly read map string except unicode map. But EE2 always assumes as Korean so unit/location/switch name etc display wrongly in EE2 (only in editor, not affect game).

Anyway this issue will going to be resolved soon™.

**Comment by bluesblue** [comment]
So that’s how it is!!!At the moment,if I set my system language as Korean,EE3 will work the same as EE2 in terms of encoding.Thank you for reply.T-T
